### ISSUE TITLE
Flaky test failures: 'stream' != 'streamstream'

### ISSUE THREAD

**Issue by fritzo** [computationalmodelling/nbval#54]
I'm seeing unexplainable test failures for cells with print statements, for example 
```
=================================== FAILURES ===================================
____________________________________ cell 8 ____________________________________
Notebook cell execution failed
Cell 8: Cell outputs differ

Input:
trace(system_test, 'unit_i', 10)

Traceback: mismatch 'output_type'
<<<<<<<<<<<< Reference output from ipynb file:
stream
============ disagrees with newly computed (test) output:
streamstream
>>>>>>>>>>>>
```
The cell in question runs a function that print()s a few lines then returns None
```
trace(system_test, 'unit_i', 10)
```
I have not been able to reproduce with a simple example, but you can see the failing notebook at
  https://github.com/fritzo/pomagma/blob/47eecf8/src/examples/definable_systems.ipynb
where I've `if 0` guarded the final cell to work around this issue.

Here's my system (running python 2.7)
```
$ pip freeze
altgraph==0.10.2
apipkg==1.4
appnope==0.1.0
appscript==1.0.1
argh==0.15.1
autoflake==0.6.6
autopep8==1.2.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
bdist-mpkg==0.5.0
BeautifulSoup==3.2.1
bleach==1.5.0
bonjour-py==0.3
boto==2.43.0
bottle==0.11.6
cdiff==0.9.6
certifi==2015.9.6.2
configparser==3.5.0
contextlib2==0.5.4
decorator==4.0.10
docformatter==0.8
entrypoints==0.2.2
enum34==1.1.6
execnet==1.4.1
flake8==3.2.1
funcsigs==1.0.2
functools32==3.2.3.post2
goftests==0.2.0
gprof2dot==2015.12.1
html5lib==0.9999999
hypothesis==3.6.1
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
isodate==0.4.8
isort==4.2.5
Jinja2==2.8.1
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.1
jupyterthemes==0.13.9
lesscpy==0.12.0
logic==0.1.10
macholib==1.5.1
Markdown==2.2.0
MarkupSafe==0.23
matplotlib==1.3.1
mccabe==0.5.3
mistune==0.7.3
mock==2.0.0
modulegraph==0.10.4
multipledispatch==0.4.9
nbconvert==5.0.0
nbformat==4.2.0
nbval==0.5
nose==1.3.7
notebook==4.3.1
numpy==1.6.2
pandocfilters==1.4.1
parsable==0.2.2
pathlib2==2.1.0
pbr==1.10.0
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
ply==3.9
-e git+git@github.com:fritzo/pomagma.git@47eecf89dda27a81f7e7900597c2ab5f0f8fbce3#egg=pomagma
prompt-toolkit==1.0.9
protobuf==2.6.1
psutil==4.4.2
ptyprocess==0.5.1
py==1.4.31
py2app==0.7.3
pycodestyle==2.2.0
pyflakes==1.3.0
pyformat==0.6
Pygments==1.5
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
PySMT==0.6.1
pytest==3.0.3
pytest-profiling==1.1.1
pytest-timeout==1.0.0
pytest-xdist==1.15.0
python-dateutil==1.5
python-magic==0.4.6
pytz==2013.7
PyYAML==3.10
pyzmq==16.0.0
qtconsole==4.2.1
requests==2.12.4
RunSnakeRun==2.0.4
s3cmd==1.5.2
scipy==0.13.0b1
selenium==2.33.0
simplegeneric==0.8.1
simplejson==3.10.0
six==1.10.0
snakeviz==0.4.0
splinter==0.5.4
SquareMap==1.0.4
stevedore==1.18.0
terminado==0.6
testpath==0.3
toolz==0.8.0
tornado==4.2.1
traitlets==4.3.1
unification==0.2.2
unify==0.2
untokenize==0.1.1
vboxapi==1.0
veritable===0.9.8preBUILD-NUMBER
virtualenv==15.0.3
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
wcwidth==0.1.7
widgetsnbextension==1.2.6
xattr==0.6.4
yapf==0.14.0
zope.interface==4.1.1
```

**Comment by fritzo** [comment]
As a workaround, I'm using `--sanitize-with=workaround.txt`, where `workaround.txt` contains

```
regex: (stream)+
replace: stream
```

**Comment by minrk** [comment]
I suspect this is related to the number of stream outputs produced by the cell varying (each stdout.flush produces a message. This number can depend on timing). nbval should be merging consecutive stream outputs into one (what we call `coalesce_streams` in nbconvert), so that the number of messages doesn't affect the output to be compared.

**Comment by fritzo** [comment]
It looks like my workaround isn't working: the tests are flaky. Does anyone have a better workaround?

**Comment by vidartf** [comment]
@minrk: Will stream outputs be coalesced in the saved notebook's output, or does nbval need to process those as well?

**Comment by vidartf** [comment]
I guess we might also have to handle `\r`. Should all streams with the same name be combined, or only subsequent ones? Are there any other gotchas? Is there a library call for handling these things (should there be)?

**Comment by vidartf** [comment]
We should also handle backspace characters, according to this code: https://github.com/jupyter/notebook/blob/e77d7ebfb060d7ce45fb85e865a2c6d8e7635900/notebook/static/base/js/utils.js#L467. However, it seems nbconvert does not do this.

**Comment by vidartf** [comment]
Is this notebook behavior going to be an issue:
![stream_coalesce](https://cloud.githubusercontent.com/assets/510760/23701411/ec59453c-03f6-11e7-9eb5-f6446689e153.png)

**Comment by vidartf** [comment]
To highlight this better, the outputs of this cell is not deterministic:
```python
import time
import numpy as np
print('Bar!', file=sys.stderr)
print('Combo breaker!', file=sys.stdout)
time.sleep(np.random.rand())
print('Foo!', file=sys.stderr)
```

**Comment by vidartf** [comment]
PS: The `stream` vs `streamstream` means that one cell had one stream, while the other cell had two. This can definitely be improved!

**Comment by takluyver** [comment]
I think we can only combine consecutive stream outputs from the same stream, to make it more consistent.

I think we had discussed a kernel change so that printing on one stream would effectively flush the other, to make output order more deterministic.

**Comment by minrk** [comment]
@vidartf to answer your question, yes consecutive outputs from the same stream will be merged into one output in the live notebook and in nbconvert during `nbconvert --execute`. The nbconvert implementation is [here](https://github.com/jupyter/nbconvert/blob/5.1.1/nbconvert/preprocessors/coalescestreams.py#L37).

**Comment by vidartf** [comment]
Fix suggested in #57.

**Comment by takluyver** [comment]
Sorry, I thought #57 was the one we already merged.

**Comment by fritzo** [comment]
Thanks for fixing this! Do you have an ETA on publishing the fix? (I'm still getting flaky errors from `nbval 0.5` on pypi.)

**Comment by takluyver** [comment]
@vidartf is there anything else you want to work on before we cut 0.6?

**Comment by vidartf** [comment]
I think we should be OK. I actually meant to get a release during PyData, but forgot about it.

**Comment by takluyver** [comment]
I have released 0.6. :-)

**Comment by fritzo** [comment]
Thank you! :+1:
